sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZKMi5tP4eAlorjJdJ+aFXwLvXNLxZg2Nc8b2ZUIws0IJdJBwAd+anGKGI34gNYPgGA3QW5Vggfusp8V++99LnfrmhFGv8cZ7yBDuHc4WPXIv0P3tCABlsLDYuTOlDiBOhCJiUPMrcyGVMIfoDBE6Bn4NxcjTg3V8BdpVKSoskftARP8OBFjnEHxPLNqvDrwd/VYMtSbEJO0DqLDvFuK2mOv1l4K0btMJrRnStlfNNtY1rCYai3NCg5D4i+UlIh4hWcISDnFCX63eYVGjPVxvcaevpYzSVwVEkboadFY4HizrefaulJZDJaqyu8djirzuswOxvNw3w7rsvhP6ic/dnd32uTumaqgxpjrjG2xPfi5nMbwFfffqAUkVBKV3/q9pYEuf28lfC1qL0JfA12VAYCEp+wu1G1GAy/IxSB2q05H9X9LTpHmLoKmHQLNEXUezymdME0lT17NEWpFlDhC4lY/EubNL/rdFfIPFxNE9IyhOAszsmeTR/zXfNg19W+ninBknfevvvV2lQpBqHE52ZiQuly3mU8jrByJVTgFvtrc9O8KzX+VdstDEzxSJ2h0gAF+Yktb0db0gD3O1xZndYH0FWAQlETFqxdQGKWwJ0dWYPmeZiuLtdd14CxiHcTF4ENsfjEfCV1LrNZPhWGziqreBZ4cJYRG7304+9Hvgq5A=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Divine-Comedy-Volume-1-Hell_1995
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy